framework:
    workflows:
        project:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Project
            initial_marking: under_moderation
            places:
                - under_moderation
                - declined
                - accepted
                - under_voting
                - voting_success
                - voting_failed
                - ended
            transitions:
                accept:
                    from: under_moderation
                    to: accepted
                decline:
                    from: under_moderation
                    to: declined
                accept_after_decline:
                    from: declined
                    to: accepted
                decline_after_accept:
                    from: accepted
                    to: declined
                start_voting:
                    from: accepted
                    to: under_voting
                cancel_voting:
                    from: under_voting
                    to: accepted
                succeed_voting:
                    from: under_voting
                    to: voting_success
                fail_voting:
                    from: under_voting
                    to: voting_failed
                end:
                    from: [accepted, voting_success, voting_failed]
                    to: ended
