framework:
    workflows:
        project:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Project
            initial_marking: under_moderation
            places:
                - under_moderation
                - declined
                - accepted
                - pre_voting
                - under_voting
                - success_voting
                - failed_voting
                - ended
            transitions:
                accept:
                    from: under_moderation
                    to: accepted
                decline:
                    from: under_moderation
                    to: declined
                accept_after_decline:
                    from: declined
                    to: accepted
                decline_after_accept:
                    from: accepted
                    to: declined
                to_pre_voting:
                    from: accepted
                    to: pre_voting
                start_voting:
                    from: pre_voting
                    to: under_voting
                cancel_voting:
                    from: under_voting
                    to: accepted
                succeed_voting:
                    from: under_voting
                    to: success_voting
                fail_voting:
                    from: under_voting
                    to: failed_voting
                end:
                    from: [accepted, success_voting, failed_voting]
                    to: ended
