<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240502182933 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE team_invite ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE team_invite ALTER id TYPE UUID USING (uuid_generate_v4())');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE team_invite ALTER id TYPE INT');
        $this->addSql('ALTER TABLE team_invite ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
